using System;
using System.Collections.Generic;

public enum Clearance
{
  INFRARED,
  RED,
  ORANGE,
  YELLOW,
  GREEN,
  BLUE,
  INDIGO,
  VIOLET,
  ULTRAVIOLET,
  ILLEGAL
}

public class Item
{
  public Clearance Clearance { get; set; }
  public string Name { get; set; }
}

public static class InventoryGenerator
{
  public static Func<Item> RandomItem = Generator.GenerateUniqueRule<Item>
  (new List<Item>
  {
    new Item { Name = "Teela-O fanclub badge", Clearance = Clearance.INFRARED },
    new Item { Name = "A pack of rubber bands", Clearance = Clearance.INFRARED },
    new Item { Name = "Folder Containing Year 213's CPU Audits", Clearance = Clearance.BLUE },
    new Item { Name = "YELLOW-Clearance Laser Barrel", Clearance = Clearance.YELLOW },
    new Item { Name = "Can of boot polish", Clearance = Clearance.INFRARED },
    new Item { Name = "Assorted lengths of wire", Clearance = Clearance.RED },
    new Item { Name = "Can of B3 (warning: very explosive) ", Clearance = Clearance.RED },
    new Item { Name = "Transtube ticket stub (used)", Clearance = Clearance.RED },
    new Item { Name = "Plastic spork", Clearance = Clearance.INFRARED },
    new Item { Name = "Red balloon", Clearance = Clearance.RED },
    new Item { Name = "Packet of algae chips", Clearance = Clearance.INFRARED },
    new Item { Name = "Visomorpain (happy) tablet", Clearance = Clearance.INFRARED },
    new Item { Name = "Rubber gloves", Clearance = Clearance.RED },
    new Item { Name = "'I Love The Computer' Badge", Clearance = Clearance.ORANGE },
    new Item { Name = "Safety pin", Clearance = Clearance.YELLOW },
    new Item { Name = "Xanitrick (wakey) tablet", Clearance = Clearance.INFRARED },
    new Item { Name = "Guide To Mutant Powers", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Can of black spraypaint", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Package of self-stick bandages", Clearance = Clearance.YELLOW },
    new Item { Name = "Handbook to Secret Society Propaganda", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Counterfeit cash (40 credits)", Clearance = Clearance.ILLEGAL },
    new Item { Name = "RED-Clearance Laser Barrel", Clearance = Clearance.RED },
    new Item { Name = "Gelgernine (very happy) tablet", Clearance = Clearance.RED },
    new Item { Name = "Rolactin (very very happy) tablet", Clearance = Clearance.BLUE },
    new Item { Name = "Plastic knife", Clearance = Clearance.INFRARED },
    new Item { Name = "Experimental B3, 23rd Flavor Edition (warning - *very* explosive)", Clearance = Clearance.ULTRAVIOLET },
    new Item { Name = "'Refer to Commitee' Rubber Stamp", Clearance = Clearance.YELLOW },
    new Item { Name = "'Denied' Rubber Stamp", Clearance = Clearance.GREEN },
    new Item { Name = "Spanner", Clearance = Clearance.RED },
    new Item { Name = "Sandallathon (sleepy) tablet", Clearance = Clearance.INFRARED },
    new Item { Name = "Genuine realfood apple", Clearance = Clearance.RED },
    new Item { Name = "Plans of nuclear reactor", Clearance = Clearance.INDIGO },
    new Item { Name = "Communist party membership card", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Propaganda phamplets from Beta Complex", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Corrective glasses", Clearance = Clearance.INFRARED },
    new Item { Name = "Biohazard sign sticker", Clearance = Clearance.BLUE },
    new Item { Name = "IntSec 'report on your friends' loyalty card (three more terminations and get a free petbot!)", Clearance = Clearance.INFRARED },
    new Item { Name = "Official History of Alpha Complex (current version)", Clearance = Clearance.RED },
    new Item { Name = "Official History of Alpha Complex (obsolete version)", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Whistle", Clearance = Clearance.RED },
    new Item { Name = "Electric drill", Clearance = Clearance.ORANGE },
    new Item { Name = "Tube of Cold Fun", Clearance = Clearance.INFRARED },
    new Item { Name = "Gas mask", Clearance = Clearance.RED },
    new Item { Name = "'Approved' Rubber Stamp", Clearance = Clearance.INDIGO },
    new Item { Name = "Can of toxic waste", Clearance = Clearance.INDIGO },
    new Item { Name = "Illegal black-market hallucinogenic tablet", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Geiger counter", Clearance = Clearance.BLUE },
    new Item { Name = "Smoke grenade", Clearance = Clearance.ORANGE },
    new Item { Name = "Frag grenade", Clearance = Clearance.YELLOW },
    new Item { Name = "Telescopalmine (truth) pill", Clearance = Clearance.GREEN },
    new Item { Name = "Old Reckoning literature", Clearance = Clearance.ULTRAVIOLET },
    new Item { Name = "BackStage Pass (can open any door in Alpha Complex, count as immediate hacking attempt)", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Self-Aiming Slugthrower (ammo sold seperatedly)", Clearance = Clearance.YELLOW },
    new Item { Name = "ME Card Belonging to Another Citizen (Mario-G-TYC-4, template since Erased)", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Vita-Yum Meal Substitute Bar", Clearance = Clearance.RED },
    new Item { Name = "Chocolyke Puff Crunchers", Clearance = Clearance.ORANGE },
    new Item { Name = "Cancer-Lite Cigarettes", Clearance = Clearance.RED },
    new Item { Name = "Smoking Boots gag—fool your friends!", Clearance = Clearance.RED },
    new Item { Name = "PlastiLaser—realistic zap noise!", Clearance = Clearance.RED },
    new Item { Name = "FunFun Firecrackers—safe for all ages!", Clearance = Clearance.RED },
    new Item { Name = "Yo-yo, lasts for hours!", Clearance = Clearance.GREEN },
    new Item { Name = "Teela-O Pocket Mirror", Clearance = Clearance.RED },
    new Item { Name = "Hottorch", Clearance = Clearance.RED },
    new Item { Name = "Instant Cleans-O-Spray", Clearance = Clearance.RED },
    new Item { Name = "Comb, red", Clearance = Clearance.RED },
    new Item { Name = "Lemonie-Moistened Towelettes", Clearance = Clearance.RED },
    new Item { Name = "Hammer", Clearance = Clearance.ORANGE },
    new Item { Name = "Dental floss", Clearance = Clearance.ORANGE },
    new Item { Name = "Crowbar", Clearance = Clearance.YELLOW },
    new Item { Name = "Nail", Clearance = Clearance.INDIGO },
    new Item { Name = "Chainsaw (electric)", Clearance = Clearance.INDIGO },
    new Item { Name = "Plastic pen, with black ink", Clearance = Clearance.INFRARED },
    new Item { Name = "Metal pen, with blank and infrared ink", Clearance = Clearance.RED },
    new Item { Name = "Metal pen, with invisible ink and invisible ink revealer", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Sneakers, black w/red stripes", Clearance = Clearance.RED },
    new Item { Name = "Heat-resistant mittens", Clearance = Clearance.ORANGE },
    new Item { Name = "FastDraw Executive laser holster", Clearance = Clearance.ORANGE },
    new Item { Name = "Pencil (disposable)", Clearance = Clearance.ORANGE },
    new Item { Name = "Official Notepad For Internal Security Snitches", Clearance = Clearance.GREEN },
    new Item { Name = "Hiking Boots", Clearance = Clearance.BLUE },
    new Item { Name = "Bullhorn, with MegaBooster!", Clearance = Clearance.RED },
    new Item { Name = "Plasticord", Clearance = Clearance.RED },
    new Item { Name = "Binoculars", Clearance = Clearance.ORANGE },
    new Item { Name = "Stopwatch", Clearance = Clearance.YELLOW },
    new Item { Name = "Slide ruler", Clearance = Clearance.YELLOW },
    new Item { Name = "Magnifying glass, bifocal", Clearance = Clearance.GREEN },
    new Item { Name = "Collapsible travel bag", Clearance = Clearance.GREEN },
    new Item { Name = "Box of matches", Clearance = Clearance.BLUE },
    new Item { Name = "Lantern, electric", Clearance = Clearance.BLUE },
    new Item { Name = "Utility knife multi-tool", Clearance = Clearance.BLUE },
    new Item { Name = "Nightvision goggles", Clearance = Clearance.INDIGO },
    new Item { Name = "Disposable lighter", Clearance = Clearance.INDIGO },
    new Item { Name = "Calculator", Clearance = Clearance.INDIGO },
    new Item { Name = "Chapstick", Clearance = Clearance.GREEN },
    new Item { Name = "Umbrella", Clearance = Clearance.VIOLET },
    new Item { Name = "Fake RED laser barrel, non-op", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Fake ORANGE barrel, non-op", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Fake YELLOW barrel, non-op", Clearance = Clearance.ILLEGAL },
    new Item { Name = "Thymoglandin (Combat Quick) tablet", Clearance = Clearance.BLUE },
    new Item { Name = "Benetridin (Videoland) tablet (hallucinogen that increases Violence and Management stats, Teela-O's favorite drug)", Clearance = Clearance.INDIGO }
  });
}